/*
 * Copyright 2016 doublegsoft.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.doublegsoft.protosys;

import com.doublegsoft.jcommons.metabean.ObjectDefinition;

/**
 * The usecase will be guessed and generated by protosys with defined model.
 *
 * @author <a href="mailto:guo.guo.gan@gmail.com">Christian Gann</a>
 * @since 1.0
 */
public class Usecase implements Comparable<Usecase> {

  private String module;

  private String name;

  private Action action;

  private ObjectDefinition object;

  public String getModule() {
    return module;
  }

  public void setModule(String module) {
    this.module = module;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Action getAction() {
    return action;
  }

  public void setAction(Action action) {
    this.action = action;
  }

  public ObjectDefinition getObject() {
    return object;
  }

  public void setObject(ObjectDefinition object) {
    this.object = object;
  }

  @Override
  public int compareTo(Usecase o) {
    int cmp = o.module.compareTo(module);
    if (cmp != 0) {
      return -cmp;
    }
    cmp = o.name.compareTo(name);
    if (cmp != 0) {
      return -cmp;
    }
    return action.compareTo(o.action);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    Usecase usecase = (Usecase) o;

    if (module != null ? !module.equals(usecase.module) : usecase.module != null) return false;
    if (name != null ? !name.equals(usecase.name) : usecase.name != null) return false;
    return action == usecase.action;

  }

  @Override
  public int hashCode() {
    int result = module != null ? module.hashCode() : 0;
    result = 31 * result + (name != null ? name.hashCode() : 0);
    result = 31 * result + (action != null ? action.hashCode() : 0);
    return result;
  }
}
